language: java
jdk:
  - openjdk8
branches:
  only:
  - master
cache:
  directories:
  - $HOME/.m2
before_install:
  # export TRAVIS_TAG is very import. Or the 'on tags: true' will not eff 
  - export TRAVIS_TAG=$(git tag --points-at HEAD)
install:
  - "echo skipped install"
script:
  - cd grpc-java-spring
  - mvn clean package
after_success:
  - "echo skipped after_success"
before_deploy:
  - "echo skipped before_deploy"
deploy:
    provider: bintray
    skip_cleanup: true
    file: target/.bintray.json
    user: l10178
    key: $BINTRAY_API_KEY
    on:
      tags: true
